config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks

  get 'new', to: 'tasks#new', as: :new
  post 'tasks', to: 'tasks#create', as: :create

  get 'tasks/:id', to: 'tasks#show', as: :task


  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)

    redirect_to tasks_path
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <script src="https://kit.fontawesome.com/8b7c6dfcaf.js" crossorigin="anonymous"></script>
</html>

app/views/tasks/_form.html.erb
  <%= form_for(@task, ) do |f| %>
    <div class="form-line">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
     <div class="form-line">
      <%= f.label :details %>
      <%= f.text_field :details %>
     </div>
    <%= f.submit class: 'submit' %>
  <% end %>

app/views/tasks/edit.html.erb
<div class="form-container">
  <h2>Update Task</h2>
  <%= render "form", task: @task %>
</div>
<div class="form-container">
  <%= link_to "◀️◀️Back to list", tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My Tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
      <% completed = task.completed %>
      <li id="list">
        <%= link_to task.title, task_path(task) %>
        <div class="list-decor">
          <i class="<%=completed ? 'fa-solid fa-square-check' : 'fa-solid fa-square' %>"></i>
          <%= link_to "🗑️", delete_path(task), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </li>
    <% end %>
  </ul>
  <hr>
  <%= link_to "➕ Add a new task", new_path %>
</div>

app/views/tasks/new.html.erb
<div class="form-container">
  <h2>Create new task</h2>
  <%= render "form", task: @task %>
</div>
<div class="form-container">
  <%= link_to "◀️◀️Back to list", tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="edit"><%= link_to "Edit this task 📝", edit_path %></div>
  <h1><%= @task.title %></h1>
  <div class="details">
    <%= @task.details %>
  </div>
  <%= link_to "Back to list", tasks_path %>
</div>